// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzqzgavlmyugnrepnrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxenF6Z2F2bG15dWducmVwbnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzMyMTcsImV4cCI6MjA2MDUwOTIxN30.1NzYl04Q1QZ91EnXnkCYgDOQoN0pme9WV4qjepPJ7Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);